ARM: 8380/1: bpf: fix NOMMU build
arch/arm/net/built-in.o: In function `bpf_jit_compile':
:(.text+0x2758): undefined reference to `set_memory_ro'
arch/arm/net/built-in.o: In function `bpf_jit_free':
:(.text+0x27ac): undefined reference to `set_memory_rw'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Change-Id: Ie020dfd1fb96bb89f81d5ce67472c79b28f7fa7e
(cherry picked from commit 1ed5f5ad9f4698b5becb9796734218a3cc234eef)